### ISSUE TITLE
Please publish final font as well

### ISSUE THREAD

**Issue by twardoch** [girish-dalvi/Modak#2]
Girish,

it would be wonderful if you could publish the final OpenType font(s) as well here in the repo. Tools change, and depending on versions of tools used, one can end up with a slightly different font, so it'd be great to have an "authoritative" version for people to download. 

The downoadable desktop fonts at Google Fonts are often heavily postprocessed, so functionality gets lost sometimes. Also, of course, Google Fonts is just one source aming many, and the fonts there aren't always up-to-date, so it'd be great to have an up-to-date location here. :) 

Great work!

Best,
Adsm

**Comment by girish-dalvi** [comment]
Hi Adam,

The final OpenType font is published in the releases section: https://github.com/girish-dalvi/Modak/releases

girish
